// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package instances

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/gogo/protobuf/types"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_InstanceID_ObjectId = regexp.MustCompile(`.*`)
var _regex_InstanceID_InstanceId = regexp.MustCompile(`.*`)

func (this *InstanceID) Validate() error {
	if !_regex_InstanceID_ObjectId.MatchString(this.ObjectId) {
		return github_com_mwitkow_go_proto_validators.FieldError("ObjectId", fmt.Errorf(`value '%v' must be a string conforming to regex ".*"`, this.ObjectId))
	}
	if !_regex_InstanceID_InstanceId.MatchString(this.InstanceId) {
		return github_com_mwitkow_go_proto_validators.FieldError("InstanceId", fmt.Errorf(`value '%v' must be a string conforming to regex ".*"`, this.InstanceId))
	}
	return nil
}

var _regex_Instance_ObjectId = regexp.MustCompile(`.*`)

func (this *Instance) Validate() error {
	if !_regex_Instance_ObjectId.MatchString(this.ObjectId) {
		return github_com_mwitkow_go_proto_validators.FieldError("ObjectId", fmt.Errorf(`value '%v' must be a string conforming to regex ".*"`, this.ObjectId))
	}
	if nil == this.Data {
		return github_com_mwitkow_go_proto_validators.FieldError("Data", fmt.Errorf("message must exist"))
	}
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *SkipLimit) Validate() error {
	if !(this.Skip > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Skip", fmt.Errorf(`value '%v' must be greater than '0'`, this.Skip))
	}
	if !(this.Skip < 3000) {
		return github_com_mwitkow_go_proto_validators.FieldError("Skip", fmt.Errorf(`value '%v' must be less than '3000'`, this.Skip))
	}
	if !(this.Limit > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '0'`, this.Limit))
	}
	if !(this.Limit < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be less than '100'`, this.Limit))
	}
	return nil
}
func (this *Count) Validate() error {
	return nil
}
